 db.restaurants.find().pretty()
 db.restaurants.find({},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
 db.restaurants.find({},{_id:0,restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
 db.restaurants.find({},{_id:0,restaurant_id:1,name:1,borough:1,"address.zipcode":1}).pretty()
 db.restaurants.find({borough:"Bronx"}).pretty()
 db.restaurants.find({borough: "Bronx"}).limit(5).pretty()
 db.restaurants.find({}).skip(5).limit(5).pretty()
 db.restaurants.find({"grades.score": {$gt: 90}}).pretty()
 db.restaurants.find({"grades.score": {$gte: 80, $lte:100}}).pretty()
 db.restaurants.find({"address.coord": {$lt: -95.754168}}).pretty()
 db.restaurants.find({$and: [{cuisine: {$ne: "American "}},{"grades.score":{$gt: 70}},{"address.coord.0": {$lt: -65.754168}}]}).pretty()
 db.restaurants.find({"grades.score":{$gt:70},cuisine:{$ne:"American "},"address.coord.0":{$lt:-65.754168}}).pretty()
 db.restaurants.find({cuisine:{$ne:"American "},"grades.grade": "A",borough:{$ne:"Brooklyn"}}).sort({"cuisine": -1}).pretty()
 db.restaurants.find({name:{$regex:"^Wil"}},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
 db.restaurants.find({name:{$regex:"ces$"}},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
 db.restaurants.find({name:{$regex:"Reg"}},{restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
 db.restaurants.find({borough:"Bronx",$or: [{"cuisine":"American "},{"cuisine":"Chinese"}]}).pretty()
 db.restaurants.find({borough:{$not:{$nin:["State Island","Bronx","Queens","Brooklyn"]}}},{_id:0,restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
 db.restaurants.find({borough:{$nin:["State Island","Bronx","Queens","Brooklyn"]}},{_id:0,restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
 db.restaurants.find({"grades.score":{$lte:10}},{_id:0,restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
 db.restaurants.find({$or: [{cuisine:"Seafood"},{name:{$regex:"Wil"}}]},{_id:0,restaurant_id:1,name:1,borough:1,cuisine:1}).pretty()
 db.restaurants.find({$and: [{"grades.grade": "A"},{"grades.score":11},{"grades.date": {"$eq": (ISODate("2014-08-11T00:00:00Z"))}}]},{_id:0,restaurant_id:1,name:1,grades:1}).pretty()
 db.restaurants.find({$and: [{"grades.1.grade": "A"},{"grades.score":9},{"grades.date": {"$eq": (ISODate("2014-08-11T00:00:00Z"))}}]},{_id:0restaurant_id:1,name:1,grades:1}).pretty()
 db.restaurants.find({$and: [{"address.coord.1":{$gt:42}},{"address.coord.1":{$lt:52}}]}).pretty()
 db.restaurants.find({},{name:1,_id:0}).sort({name:1}).pretty()
 db.restaurants.find({},{name:1,_id:0}).sort({name:-1}).pretty()
 db.restaurants.find({},{cusine:1,borough:1,_id:0}).sort({cusine:1,"address.street":-1}).pretty()
